import { connectDB } from '@/lib/db';
import Product from '@/models/Product';
import { NextRequest, NextResponse } from 'next/server';

const sampleProducts = [
  // ───── MEN'S COLLECTION ─────
  {
    name: 'Lensify Aviator Classic',
    description: 'Iconic aviator frames in gold titanium. A timeless style for every occasion.',
    price: 12500,
    discount: 10,
    category: 'men',
    shape: 'oval',
    color: 'gold',
    brand: 'Lensify Pro',
    material: 'titanium',
    imageUrl: '/products/men-1.jpg',
    stock: 50,
    rating: 4.9,
    reviews: 312,
  },
  {
    name: 'Lensify Wayfarer Black',
    description: 'Classic wayfarer silhouette in premium matte black acetate. Bold and effortlessly stylish.',
    price: 7500,
    discount: 5,
    category: 'men',
    shape: 'rectangle',
    color: 'black',
    brand: 'Lensify Pro',
    material: 'acetate',
    imageUrl: '/products/men-2.jpg',
    stock: 48,
    rating: 4.7,
    reviews: 189,
  },
  {
    name: 'Lensify Sport Rectangle',
    description: 'Performance rectangular frames with UV400 lenses for active lifestyles.',
    price: 8500,
    discount: 15,
    category: 'men',
    shape: 'rectangle',
    color: 'matte black',
    brand: 'Lensify Sport',
    material: 'plastic',
    imageUrl: '/products/men-3.jpg',
    stock: 58,
    rating: 4.6,
    reviews: 223,
  },
  {
    name: 'Lensify Executive Silver',
    description: 'Slim titanium rectangular frames in brushed silver. Perfect for the modern professional.',
    price: 9500,
    discount: 0,
    category: 'men',
    shape: 'rectangle',
    color: 'silver',
    brand: 'Lensify Executive',
    material: 'titanium',
    imageUrl: '/products/men-4.jpg',
    stock: 45,
    rating: 4.8,
    reviews: 145,
  },
  {
    name: 'Lensify Round Gunmetal',
    description: 'Sophisticated round frames in gunmetal finish. Refined style for the modern gentleman.',
    price: 11000,
    discount: 8,
    category: 'men',
    shape: 'round',
    color: 'gunmetal',
    brand: 'Lensify Executive',
    material: 'titanium',
    imageUrl: '/products/men-5.jpg',
    stock: 38,
    rating: 4.7,
    reviews: 134,
  },
  {
    name: 'Lensify Clubmaster Tortoise',
    description: 'Vintage-inspired clubmaster design in warm tortoiseshell acetate with gold accents.',
    price: 8000,
    discount: 10,
    category: 'men',
    shape: 'square',
    color: 'tortoiseshell',
    brand: 'Lensify Vintage',
    material: 'acetate',
    imageUrl: '/products/men-6.jpg',
    stock: 52,
    rating: 4.6,
    reviews: 201,
  },
  {
    name: 'Lensify Havana Oval',
    description: 'Warm havana oval frames with a classic feel and modern proportions.',
    price: 9000,
    discount: 12,
    category: 'men',
    shape: 'oval',
    color: 'havana',
    brand: 'Lensify Classic',
    material: 'acetate',
    imageUrl: '/products/men-7.jpg',
    stock: 40,
    rating: 4.8,
    reviews: 156,
  },
  {
    name: 'Lensify Navy Hexagon',
    description: 'Contemporary hexagon frames in deep navy blue. Stand out from the crowd.',
    price: 6500,
    discount: 20,
    category: 'men',
    shape: 'hexagon',
    color: 'navy',
    brand: 'Lensify Pro',
    material: 'acetate',
    imageUrl: '/products/men-8.jpg',
    stock: 34,
    rating: 4.5,
    reviews: 103,
  },

  // ───── WOMEN'S COLLECTION ─────
  {
    name: 'Lensify Round Gold',
    description: 'Elegant round metal frames in shiny gold. Delicate and feminine.',
    price: 10500,
    discount: 12,
    category: 'women',
    shape: 'round',
    color: 'gold',
    brand: 'Lensify Luxe',
    material: 'titanium',
    imageUrl: '/products/women-1.jpg',
    stock: 46,
    rating: 4.8,
    reviews: 267,
  },
  {
    name: 'Lensify Cat Eye Black',
    description: 'Retro cat-eye frames in sleek black acetate. Bold femininity meets timeless style.',
    price: 6000,
    discount: 15,
    category: 'women',
    shape: 'cat-eye',
    color: 'black',
    brand: 'Lensify Luxe',
    material: 'acetate',
    imageUrl: '/products/women-2.jpg',
    stock: 54,
    rating: 4.7,
    reviews: 189,
  },
  {
    name: 'Lensify Rose Gold Rectangle',
    description: 'Slim rectangular frames in elegant rose gold titanium. Chic and modern.',
    price: 11500,
    discount: 8,
    category: 'women',
    shape: 'rectangle',
    color: 'rose gold',
    brand: 'Lensify Luxe',
    material: 'titanium',
    imageUrl: '/products/women-3.jpg',
    stock: 33,
    rating: 4.9,
    reviews: 145,
  },
  {
    name: 'Lensify Oval Havana',
    description: 'Oversized oval frames in warm havana acetate. Vintage charm with modern proportions.',
    price: 7000,
    discount: 10,
    category: 'women',
    shape: 'oval',
    color: 'havana',
    brand: 'Lensify Classic',
    material: 'acetate',
    imageUrl: '/products/women-4.jpg',
    stock: 28,
    rating: 4.7,
    reviews: 156,
  },
  {
    name: 'Lensify Cat Eye Pink',
    description: 'Fashionable cat-eye in blush pink gradient. Feminine, playful and elegant.',
    price: 7500,
    discount: 20,
    category: 'women',
    shape: 'cat-eye',
    color: 'pink',
    brand: 'Lensify Luxe',
    material: 'acetate',
    imageUrl: '/products/women-5.jpg',
    stock: 58,
    rating: 4.5,
    reviews: 156,
  },
  {
    name: 'Lensify Hexagon Brown',
    description: 'Retro hexagon frames in warm brown acetate. Unique shape for a distinctive look.',
    price: 5500,
    discount: 22,
    category: 'women',
    shape: 'hexagon',
    color: 'brown',
    brand: 'Lensify Vintage',
    material: 'acetate',
    imageUrl: '/products/women-6.jpg',
    stock: 51,
    rating: 4.5,
    reviews: 145,
  },
  {
    name: 'Lensify Square Purple',
    description: 'Bold oversized square frames in rich purple acetate. Make a statement.',
    price: 8500,
    discount: 10,
    category: 'women',
    shape: 'square',
    color: 'purple',
    brand: 'Lensify Luxe',
    material: 'acetate',
    imageUrl: '/products/women-7.jpg',
    stock: 32,
    rating: 4.8,
    reviews: 142,
  },
  {
    name: 'Lensify Round Mirrored',
    description: 'Trendy round frames with gold mirror lenses. Eye-catching for bold fashionistas.',
    price: 9000,
    discount: 25,
    category: 'women',
    shape: 'round',
    color: 'gold',
    brand: 'Lensify Luxe',
    material: 'titanium',
    imageUrl: '/products/women-8.jpg',
    stock: 64,
    rating: 4.6,
    reviews: 178,
  },

  // ───── UNISEX COLLECTION ─────
  {
    name: 'Lensify Clear Round',
    description: 'Minimalist round frames in crystal clear acetate. Versatile and effortlessly modern.',
    price: 5000,
    discount: 18,
    category: 'unisex',
    shape: 'round',
    color: 'clear',
    brand: 'Lensify Pro',
    material: 'acetate',
    imageUrl: '/products/unisex-1.jpg',
    stock: 120,
    rating: 4.5,
    reviews: 334,
  },
  {
    name: 'Lensify Tortoise Rectangle',
    description: 'Classic tortoiseshell rectangular frames. Timeless design that works for everyone.',
    price: 7000,
    discount: 15,
    category: 'unisex',
    shape: 'rectangle',
    color: 'tortoiseshell',
    brand: 'Lensify Classic',
    material: 'acetate',
    imageUrl: '/products/unisex-2.jpg',
    stock: 85,
    rating: 4.7,
    reviews: 289,
  },
  {
    name: 'Lensify Minimalist Square',
    description: 'Clean minimalist square frames in brushed silver titanium. Less is more.',
    price: 7500,
    discount: 10,
    category: 'unisex',
    shape: 'square',
    color: 'silver',
    brand: 'Lensify Executive',
    material: 'titanium',
    imageUrl: '/products/unisex-3.jpg',
    stock: 45,
    rating: 4.6,
    reviews: 178,
  },
  {
    name: 'Lensify Blue Light Oval',
    description: 'Lightweight oval frames with blue light blocking lenses. Perfect for screen time.',
    price: 6000,
    discount: 20,
    category: 'unisex',
    shape: 'oval',
    color: 'black',
    brand: 'Lensify Pro',
    material: 'plastic',
    imageUrl: '/products/unisex-4.jpg',
    stock: 95,
    rating: 4.5,
    reviews: 412,
  },
  {
    name: 'Lensify Havana Square',
    description: 'Warm havana square frames. Easygoing and refined for any style.',
    price: 8000,
    discount: 9,
    category: 'unisex',
    shape: 'square',
    color: 'havana',
    brand: 'Lensify Classic',
    material: 'acetate',
    imageUrl: '/products/unisex-5.jpg',
    stock: 46,
    rating: 4.7,
    reviews: 173,
  },
  {
    name: 'Lensify Hexagon Clear',
    description: 'Modern hexagon shape in crystal clear acetate. Geometric flair for any face shape.',
    price: 5500,
    discount: 18,
    category: 'unisex',
    shape: 'hexagon',
    color: 'clear',
    brand: 'Lensify Classic',
    material: 'acetate',
    imageUrl: '/products/unisex-6.jpg',
    stock: 61,
    rating: 4.4,
    reviews: 134,
  },
  {
    name: 'Lensify Sage Green Round',
    description: 'Calming sage green round frames in lightweight acetate. Fresh and nature-inspired.',
    price: 6500,
    discount: 16,
    category: 'unisex',
    shape: 'round',
    color: 'green',
    brand: 'Lensify Vintage',
    material: 'acetate',
    imageUrl: '/products/unisex-7.jpg',
    stock: 47,
    rating: 4.4,
    reviews: 96,
  },
  {
    name: 'Lensify Classic Black Rectangle',
    description: 'Everyday essential rectangular frames in glossy black. Simple, clean and reliable.',
    price: 5000,
    discount: 12,
    category: 'unisex',
    shape: 'rectangle',
    color: 'black',
    brand: 'Lensify Pro',
    material: 'plastic',
    imageUrl: '/products/unisex-8.jpg',
    stock: 98,
    rating: 4.4,
    reviews: 356,
  },
  // ───── CONTACT LENSES COLLECTION ─────
  {
    name: 'Lensify Aqua Blue Contacts',
    description: 'Stunning aqua blue colored contact lenses. Transform your look instantly with vivid ocean blue color.',
    price: 3500,
    discount: 10,
    category: 'contacts',
    shape: 'round',
    color: 'blue',
    brand: 'Lensify Luxe',
    material: 'hydrogel',
    imageUrl: '/products/contacts-1.jpg',
    stock: 80,
    rating: 4.7,
    reviews: 234,
  },
  {
    name: 'Lensify Emerald Green Contacts',
    description: 'Rich emerald green lenses that give your eyes a captivating natural look.',
    price: 3500,
    discount: 10,
    category: 'contacts',
    shape: 'round',
    color: 'green',
    brand: 'Lensify Luxe',
    material: 'hydrogel',
    imageUrl: '/products/contacts-2.jpg',
    stock: 75,
    rating: 4.6,
    reviews: 189,
  },
  {
    name: 'Lensify Honey Brown Contacts',
    description: 'Warm honey brown lenses for a natural yet enhanced eye color. Perfect for everyday wear.',
    price: 3200,
    discount: 5,
    category: 'contacts',
    shape: 'round',
    color: 'brown',
    brand: 'Lensify Classic',
    material: 'hydrogel',
    imageUrl: '/products/contacts-3.jpg',
    stock: 90,
    rating: 4.8,
    reviews: 312,
  },
  {
    name: 'Lensify Silver Grey Contacts',
    description: 'Cool silver grey lenses for a mysterious and modern look. Ideal for special occasions.',
    price: 3800,
    discount: 15,
    category: 'contacts',
    shape: 'round',
    color: 'grey',
    brand: 'Lensify Pro',
    material: 'hydrogel',
    imageUrl: '/products/contacts-4.jpg',
    stock: 65,
    rating: 4.5,
    reviews: 156,
  },
  {
    name: 'Lensify Violet Purple Contacts',
    description: 'Bold and beautiful violet purple lenses. Make a statement with these stunning colored contacts.',
    price: 4000,
    discount: 12,
    category: 'contacts',
    shape: 'round',
    color: 'purple',
    brand: 'Lensify Luxe',
    material: 'hydrogel',
    imageUrl: '/products/contacts-5.jpg',
    stock: 55,
    rating: 4.6,
    reviews: 143,
  },
  {
    name: 'Lensify Ice Blue Contacts',
    description: 'Striking ice blue lenses for a dramatic and unforgettable look.',
    price: 3800,
    discount: 8,
    category: 'contacts',
    shape: 'round',
    color: 'blue',
    brand: 'Lensify Pro',
    material: 'silicone hydrogel',
    imageUrl: '/products/contacts-6.jpg',
    stock: 70,
    rating: 4.7,
    reviews: 198,
  },
];

async function doSeed() {
  await connectDB();
  await Product.deleteMany({});
  const created = await Product.insertMany(sampleProducts);
  return {
    message: 'Database seeded successfully',
    count: created.length,
  };
}

export async function GET(request: NextRequest) {
  try {
    const result = await doSeed();
    return NextResponse.json(result);
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json(
      { error: 'Failed to seed database', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const result = await doSeed();
    return NextResponse.json(result);
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json(
      { error: 'Failed to seed database', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}